controller_list:
  - name: fake_minibot_arm_controller
    joints:
      - base_joint
      - shoulder_joint
      - upperarm_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint
      - flange_joint
  - name: fake_palm_controller
    joints:
      - knuckle_joint
  - name: fake_hand_controller
    joints:
      - finger_joint
initial:
  - group: minibot_arm
    pose: relaxed
  - group: palm
    pose: gripping
  - group: hand
    pose: open
