rate: 25
controller_list:
  - name: fake_minibot_controller
    joints:
      - base_joint
      - shoulder_joint
      - upperarm_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint
      - flange_joint
      - knuckle_joint
      - finger_joint
initial:
  - group: minibot_arm
    pose: relaxed
  - group: minibot_gripper
    pose: egggrip
