# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# As MoveIt! does not support jerk limits, the acceleration limits provided here are the highest values that guarantee
# that no jerk limits will be violated. More precisely, applying Euler differentiation in the worst case (from min accel
# to max accel in 1 ms) the acceleration limits are the ones that satisfy
# max_jerk = (max_acceleration - min_acceleration) / 0.001

# units are
#    position: radians
#    velocity: radians/sec
#    acceleration: radians/sec^2


joint_limits:
  base_joint:
    has_velocity_limits: true
    max_velocity: 5.0             # Herkulex DRS-402: 0.162s / 60 = 6.28 rad/s
    has_acceleration_limits: true
    max_acceleration: 0.5         # assumption is max speed in 0.5s, a=v/t = 1.2 rad/s^2
  shoulder_joint:
    has_velocity_limits: true
    max_velocity: 4.0             # 2xHerkulex DRS-402
    has_acceleration_limits: true
    max_acceleration: 1.25      
  upperarm_joint:
    has_velocity_limits: true
    max_velocity: 4.0         # Herkulex DRS-602
    has_acceleration_limits: true
    max_acceleration: 1.5
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 2.0
  forearm_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 2.5
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_joint:
    has_velocity_limits: true
    max_velocity: 2.0      # gear 8.5/4.5 and worm with 1:2.5 = 1:0.7, 360° respr. 60° finger,  
    has_acceleration_limits: true
    max_acceleration: 5.0

