 controller_list:
  - name: position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_joint
      - shoulder_joint
      - upperarm_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint
      - flange_joint
